return {
["rhox_valbrand_nor_marauder_chieftain_horde"] = {"rhox_valbrand_art_set_nor_marauder_chieftain_01","rhox_valbrand_art_set_nor_marauder_chieftain_02","rhox_valbrand_art_set_nor_marauder_chieftain_03","rhox_valbrand_art_set_nor_marauder_chieftain_04"},
["rhox_volrik_chs_sorcerer_lord_tzeentch_mtze"] = {"rhox_volrik_art_set_chs_sorcerer_lord_tzeentch_mtze_01","rhox_volrik_art_set_chs_sorcerer_lord_tzeentch_mtze_02","rhox_volrik_art_set_chs_sorcerer_lord_tzeentch_mtze_03","rhox_volrik_art_set_chs_sorcerer_lord_tzeentch_mtze_04","rhox_volrik_art_set_chs_sorcerer_lord_tzeentch_mtze_05"},
["rhox_torinubar_convoy"] = {"rhox_torinubar_convoy_01","rhox_torinubar_convoy_02","rhox_torinubar_convoy_03","rhox_torinubar_convoy_04"},
["wh3_dlc20_chs_sorcerer_slaanesh_msla"] = {"rhox_dolmance_art_set_chs_sorcerer_slaanesh_msla_01","rhox_dolmance_art_set_chs_sorcerer_slaanesh_msla_02","rhox_dolmance_art_set_chs_sorcerer_slaanesh_msla_03","rhox_dolmance_art_set_chs_sorcerer_slaanesh_msla_04","rhox_dolmance_art_set_chs_sorcerer_slaanesh_msla_05"},
["wh3_dlc20_chs_sorcerer_shadows_msla"] = {"rhox_dolmance_art_set_chs_sorcerer_shadows_msla_01","rhox_dolmance_art_set_chs_sorcerer_shadows_msla_02","rhox_dolmance_art_set_chs_sorcerer_shadows_msla_03","rhox_dolmance_art_set_chs_sorcerer_shadows_msla_04","rhox_dolmance_art_set_chs_sorcerer_shadows_msla_05"}
};

